apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-net-gateway
  labels:
    app: api-net-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-net-gateway
  template:
    metadata:
      labels:
        app: api-net-gateway
    spec:
      containers:
      - name: api-net-gateway
        image: ride-sharing/api-net-gateway
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 20
          periodSeconds: 20
