apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-flutter
  labels:
    app: ecom-flutter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-flutter
  template:
    metadata:
      labels:
        app: ecom-flutter
    spec:
      containers:
      - name: ecom-flutter
        image: ride-sharing/ecom-flutter
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          periodSeconds: 20
